server:
  port: 9000
  address: cloud.test.com
spring:
  application:
    name: system
  profiles:
    active: dev

logging:
  config: classpath:logback.groovy

---
spring:
  application:
    name: system
  profiles: dev

---
spring:
  application:
    name: system
  profiles: test
---
spring:
  application:
    name: system
  profiles: prod
