server:
  port: 9000
  address: cloud.test.com
eureka:
  instance:
    prefer-ip-address: true
    ip-address: cloud.test.com
  client:
    service-url:
      defaultZone: http://admin:admin123@cloud.test.com:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 20


spring:
  profiles:
    active: dev
  datasource:
    username: root
    url: jdbc:mysql://cloud.db.com:3306/system?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    password: root
  application:
    name: system
logging:
  config: classpath:logback.groovy
