server:
  port: 9000
  address: cloud.test.com
spring:
  application:
    name: system
  profiles:
    active: dev


---
spring:
  profiles: dev
---
spring:
  application:
    name: system
  profiles: test
---
spring:
  application:
    name: system
  profiles: prod
