spring:
  application:
    name: ConfigServer
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local

server:
  port: 10003
  address: localhost

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.146
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 20
