server:
  port: 10005

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin123@cloud.test.com:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path= /system/**
          filters:
            - SwaggerHeaderFilter
            - StripPrefix=1