server:
  port: 10005
spring:
  application:
    name: Gateway

  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
#      - id: user
#        uri: lb://user
#        predicates:
#        - Path=${server.servlet.context-path}/user/**
#        filters:
#        - SwaggerHeaderFilter
#        - StripPrefix= 1
      - id: system
        uri: http://localhost:9000
#        uri: lb://system
        predicates:
        - Path= /system/**
        filters:
#        - SwaggerHeaderFilter
        - StripPrefix= 1


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.146
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5
#logging:
#  level:
#    root: DEBUG

