server:
  port: 10005

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin123@cloud.test.com:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5

spring:
  application:
    name: Gateway
  redis:
    host: cloud.db.com
    password: admin123
    port: 6379

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path= /system/**
          filters:
            # https://segmentfault.com/a/1190000015700907
            - SwaggerHeaderFilter
#            - StripPrefix=0
            - PrefixPath=/system
            - AddRequestHeader=X-Request-id, system
            - AddRequestParameter=param, 10
            - AddResponseHeader= X-Response-id, system
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
      default-filters:
      - name: RequestRateLimiter
        args:
          redis-rate-limiter.replenishRate: 1  #令牌桶的容积
          redis-rate-limiter.burstCapacity: 1  #流速 每秒
          rate-limiter: "#{@defaultRedisRateLimiter}"  #SPEL表达式去的对应的bean
          key-resolver: "#{@remoteAddressKeyResolver}" #SPEL表达式去的对应的bean
