server:
  port: 10005
spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:9000
          predicates:
            - Path=${server.servlet.context-path}/user/**
          filter:
            - StripPrefix=0
        - id: system
          uri: http://localhost:9001
          predicates:
            - Path=${server.servlet.context-path}/system/**
          filter:
          - StripPrefix=0


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.146
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 5
