server:
  port: 10000
spring:
  application:
    name: EurekaServer
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin123
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://${server.address:localhost}:${server.port}/eureka/
    fetch-registry: false
#    registry-fetch-interval-seconds: 30
  instance:
    non-secure-port-enabled: false
    hostname: localhost
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000
