server:
  port: 9001

spring:
  application:
    name: user
  datasource:
  url: 
    username:
    password:

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.146
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:10000/eureka/
    fetch-registry: true
    registry-fetch-interval-seconds: 20