server:
  port: 9001
  address: cloud.test.com
spring:
  application:
    name: user
  profiles:
    active: dev

---
spring:
  application:
    name: user
  profiles: dev

---
spring:
  application:
    name: user
  profiles: test

---
spring:
  application:
    name: user
  profiles: prod


