
server:
  port: 10006
  address: cloud.test.com
spring:
  application:
    name: message
  profiles:
    active: dev
logging:
  config: classpath:logback.groovy

---
spring:
  profiles: dev
  jpa:
    show-sql: true
  rabbitmq:
    host: cloud.db.com
    port: 5672
    username: guest
    password: guest

---
spring:
  profiles: h2
  datasource:
    username: root
    password: root
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2
    h2:
      console:
        enabled: true
        path: /h2
        settings:
          web-allow-others: true
